### ISSUE TITLE
[GIP] password strength check

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/improvement-proposals#2]
### [FR] Qui ?

Camptocamp, avec le soutien financier de la [MEL](https://www.lillemetropole.fr/)

### [EN] Who ?

Camptocamp, with financial support from [MEL](https://www.lillemetropole.fr/)

### [FR] Elements concernés

Console

### [EN] Target Module

Console

### [FR] Quoi ?

En tant qu'utilisateur de la plateforme, je dois créer un mot de passe respectant un certain nombre de critères définis par l'administrateur de la plateforme :

- nombre de caractères
- classes de caractères obligatoires (parmi minuscules, majuscule, chiffres, caractères spéciaux)

Dans le cas contraire, l'application n'accepte pas le mot de passe et indique la raison de manière claire (quel critère n'est pas satisfait).

### [EN] What ?

As a user, I should create a password matching criteria defined by a plateform-admin : 

- number of chars
- mandatory classes among lowercase, uppercase, numbers, special chars

If not, the platform should refuse the password with a clear message (which criteria is not met)

### [FR] Pourquoi ?

Augmenter le niveau de sécurité des données fournies par la plateforme

### [EN] Why ?

Securing the platform-provided data

### [FR] Comment ?

Server-side checks

### [EN] How ?

Vérifications côté serveur

### [FR] Identifiez-vous d'éventuels problèmes et avez-vous une idée sur la façon de les circonvenir ?

- ~est-ce que ces critères sont suffisamment génériques pour être implémentés dans toute IDG geOrchestra ? (on me souffle par exemple que forcer les types de caractères obligatoires n'est pas une bonne façon d'augmenter la sécurité des mots de passe)~

### [EN] Any potential pitfalls and ways to circumvent them ?

- ~are these criteria generic enough for any geOrchestra instance ? (I've heard people say that forcing chars from 4 classes is not a recommended way to increase password security)~

### [FR] Quand ?

Implémentation en cours, sortie prévue avec la version 23.1.

### [EN] When ?

Ongoing implementation, targeting release 23.1

### State of the vote:

| PSC members              | vote |
|-------------------------:|------|
| Fabrice Phung            |   +1   |
| François Van Der Biest   |   +1   |
| Pierre Mauduit           |   +1   |
| Landry Breuil            |  +1   |
| Stéphane Mével-Viannay   |   +1   |
| Maël Reboux              |  +1    |
| Pierre Jégo              |   +1   |
| Jean Pommier             |  +1    |
| Catherine Piton-Morales  |   +1   |

**Comment by MarcScha** [comment]
bonjour,
16 caractères semblent excessifs. 
- il faudrait(fallait en 2021) 5 ans pour casser par force brute un mdp de 10 caractères avec au moins un caractère de chacune de ces classes : minuscules, majuscule, chiffres, caractères spéciaux (https://www.cadre21.org/ressources/se-premunir-contre-les-cyberpirates/)
- la CNIL recommande au moins 12 caractères et 4 types différents (https://www.cnil.fr/fr/les-conseils-de-la-cnil-pour-un-bon-mot-de-passe)
- et "Whilst not a password panacea, using 'three random words' is still better than enforcing arbitrary complexity requirements" (https://www.ncsc.gov.uk/blog-post/the-logic-behind-three-random-words).
Mais si c'est paramétrable ....
Marc

**Comment by fphg** [comment]
thanks for the GIP, some remarks

- password policy is a subset of corp security policy. georchestra has no autority to define such policy. therefore the GIP shall describe how "ideally, configurable by platform admin" is implemented to ensure various policies compliance
- georchestra is international ; therefore it shall only be be CNIL compliant, not CNIL defined
- pitfall : assuming this new ruleset is implemented, are pre-existing users impacted ? how does the system react if policy changes ?
- rem : some corp may also ask for password timeout and  2 factor auth in the future

**Comment by landryb** [comment]
i agree with all of the remarks from @fphg :) enforcing character classes "was" imo a best practice, but it'll never be as useful/strong as using diceware-like passwords (https://en.wikipedia.org/wiki/Diceware), eg 4 random words taken from a dictionary.. mandatory xkcd: https://xkcd.com/936/

also, why serverside checks ? it cant be to check all existing passwords, since by default afaict only their hashes are stored in LDAP.. and right now it's only done client side - but i agree an attacker can totally circumvent that by talking directly to the console API.. so serverside check is more secure (in addition to a client side check for rapid user feedback ?).

wrt the GIP itself, :+1: on the general idea in all cases, being able to specify a policy is much welcomed. I see two optional config fields for the admin:
- passwd length (default to 12, minimum allowed 10 ?)
- char classes required (eg alpha, alphanumeric, mixedcase alpha, all previous plus specialchars ? with default to the latter)
and ofc the policy should be clearly shown to the user above the passwd field.

Changing the default policy, and not making it configurable, for all platforms... not so much :)

**Comment by catmorales** [comment]
Comment ça se comporte quand on est branché sur un Ad ou un LDAP externe ?

**Comment by jusabatier** [comment]
Si ça passe par du SASL, il me semble que le fait de redéfinir le MDP fait sauter le binding et change le MDP uniquement pour Georchestra.

**Comment by pmauduit** [comment]
> Si ça passe par du SASL, il me semble que le fait de redéfinir le MDP fait sauter le binding et change le MDP uniquement pour Georchestra.

La console ne s'intéresse qu'à l'OpenLDAP de geOrchestra (on peut le voir comme un client web pour administrer son OpenLDAP georchestrea), et n'est pas fait pour administrer autre chose. Donc cela ne pourra pas avoir d'influence sur un annuaire distant.

**Comment by fvanderbiest** [comment]
I've just updated the proposal and voted.
Please vote above. Thanks !

**Comment by catmorales** [comment]
voted

**Comment by pierrejego** [comment]
voted

**Comment by landryb** [comment]
readded my support :)

**Comment by fphg** [comment]
+1

**Comment by vfabry** [comment]
+1

**Comment by fvanderbiest** [comment]
> +1 no rights in editing ;)

@smevel now you can (check your emails first ;-)

**Comment by fvanderbiest** [comment]
Implemented with geOrchestra 23.0
