### ISSUE TITLE
[GIP] password expiration policy

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/improvement-proposals#3]
### [FR] Qui ?

Camptocamp, avec le soutien de la MEL

### [EN] Who ?

Camptocamp, with MEL's support

### [FR] Elements concernés

console / gateway

### [EN] Target Module

console / gateway

### [FR] Quoi ?

En tant qu’utilisateur avec un compte local, je dois renouveler mon mot de passe au bout d'une période configurable par l'administrateur si je veux continuer à pouvoir me connecter sur la plateforme.

### [EN] What ?

We would like users to renew their password every X months, with the inability to reuse the last password.

### [FR] Pourquoi ?

Sécurité

### [EN] Why ?

Security

### [FR] Comment ?

Règles métier :
 * la fonctionnalité doit être contribuée au tandem gateway/console
 * elle ne concerne que les utilisateurs enregistrés sur le LDAP local à geOrchestra
 * la fonctionnalité est activable par modification d'une option dans datadir/console/console.properties. Par défaut elle est désactivée.
 * La durée de conservation d'un mot de passe est fixée en mois dans datadir/console/console.properties. La valeur par défaut est de 12 mois. Alternativement ces 2 options seront réunies en une seule qui, si elle est positionnée à 0, désactive la fonctionnalité.
 * Si le délai fixé est dépassé, la connexion échouera avec un message spécifique : "Votre mot de passe a expiré et doit être renouvelé, [cliquez ici]." Plus ergonomique : la page suivante sera affichée directement, et elle présentera ce message.
 * Au clic sur le lien, l'utilisateur sera dirigé vers une nouvelle page /console/account/passwordUpdate qui demandera l'ancien mot de passe et le nouveau.
 * Si l'ancien mot de passe est valide, l'utilisateur sera redirigé vers la route par défaut de la gateway avec le paramètre forçant la connection (?login), ce qui devrait faire apparaître le formulaire de connexion.
 * Si l'ancien mot de passe est invalide, la page sera représentée, avec un message d'erreur adapté.
 * L'utilisateur ne peut pas réutiliser son mot de passe précédent. Si c'est le cas, un message d'erreur adapté sera présenté.

### [EN] How ?

Rules :
 * feature will be contributed to the gateway/console tandem
 * only for local LDAP users
 * activated by means of an option in datadir/console/console.properties. Disabled by default.
 * password retention is set in months in datadir/console/console.properties. Default is 12 months. Alternatively this option can be used to disable the feature, by setting it to 0.
 * when the password is osbsolete, connexion fails with "Your password is expired, please [renew here]." Probably a better UX if the following page displays at once with this message.
 * When clicking the link, user gets redirected to /console/account/passwordUpdate which asks for the old and the new password.
 * if the previous password is correct user is redirected to the gateway's default route with the ?login parameter. This should trigger the login screen.
 * if the previous password is incorrect, the same page is shown again, with an error message.
 * user cannot reuse the same password. If passwords match, an error message will be shown.

### [FR] Identifiez-vous d'éventuels problèmes et avez-vous une idée sur la façon de les circonvenir ?

-

### [EN] Any potential pitfalls and ways to circumvent them ?

-

### [FR] Quand ?

Release 23.1

### [EN] When ?

Release 23.1

### State of the vote:

| PSC members              | vote |
|-------------------------:|------|
| Fabrice Phung            |      |
| François Van Der Biest   |      |
| Pierre Mauduit           |      |
| Landry Breuil            |      |
| Stéphane Mével-Viannay   |      |
| Maël Reboux              |      |
| Pierre Jégo              |      |
| Jean Pommier             |      |
| Catherine Piton-Morales  |      |

**Comment by fvanderbiest** [comment]
PSC please speak up :-)

**Comment by landryb** [comment]
> PSC please speak up :-)

sure, but i dont think this GIP (nor #2?) has been brought up to the users list, per item 1 of https://github.com/georchestra/improvement-proposals/blob/main/README_en.md#process ...

**Comment by fvanderbiest** [comment]
> sure, but i dont think this GIP (nor #2?) has been brought up to the users list, per item 1 of https://github.com/georchestra/improvement-proposals/blob/main/README_en.md#process ...

Yup. Fixed ATM.
Maybe this should be removed, as it puts an additional burden on GIP creators.
I suppose that those who are interested in such thinks are already watching the current repository.

**Comment by landryb** [comment]
> > sure, but i dont think this GIP (nor #2?) has been brought up to the users list, per item 1 of https://github.com/georchestra/improvement-proposals/blob/main/README_en.md#process ...
> 
> Yup. Fixed ATM. Maybe this should be removed, as it puts an additional burden on GIP creators. I suppose that those who are interested in such thinks are already watching the current repository.

Sorry, but i thought the point of doing GIPs was to clearly communicate to **everyone** interested in/using georchestra what are the 'large user-facing' changes to come. So it **has** to be widely communicated ... i dont think we can assume everyone watches this repo (right now, that's only 16 github accounts..) or require ppl to subscribe to yet another different channel..

**Comment by fvanderbiest** [comment]
Well, this does not raise the crowds...

**Comment by landryb** [comment]
But at least ppl have had the occasion to raise concerns, before the GIP is put up for vote :)

**Comment by fvanderbiest** [comment]
I've just updated the proposal description to reflect latest discussions.

**Comment by fvanderbiest** [comment]
Implemented on master for the upcoming 23.1 release.
